language: scala

dist: trusty

jdk:
  - oraclejdk8

script: .travis/build.sh

sudo: false

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

before_cache:
  - find $HOME/.ivy2/cache/net.iakovlev -depth -name "*timeshape" -exec rm -r {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete

branches:
  only:
    - master
